# fly.toml app configuration file generated for memo-2406 on 2024-06-13T14:17:07+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'memo-2406'
primary_region = 'sjc'

[build]
  builder = "flyio/builder"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
